import localFont from "next/font/local"
import { Inter } from "next/font/google"
import "./globals.css"
import Providers from "@/components/session-provider"
import { Toaster } from "sonner"

const myFont = localFont({
  src: "./fonts/Switzer-Regular.otf",
  display: "swap",
  variable: "--font-switzer",
})

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} ${inter.className} lg:w-9/12 lg:m-auto lg:min-h-screen mx-5`}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
